// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/hello.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Helloworld
{
    /// <summary>
    /// The greeting service definition.
    /// </summary>
    public static partial class Greeter
    {
        static readonly string __ServiceName = "helloworld.Greeter";

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
        {
#if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
            if (message is global::Google.Protobuf.IBufferMessage)
            {
                context.SetPayloadLength(message.CalculateSize());
                global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
                context.Complete();
                return;
            }
#endif
            context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static class __Helper_MessageCache<T>
        {
            public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
        {
#if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
            if (__Helper_MessageCache<T>.IsBufferMessage)
            {
                return parser.ParseFrom(context.PayloadAsReadOnlySequence());
            }
#endif
            return parser.ParseFrom(context.PayloadAsNewBuffer());
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Helloworld.HelloRequest> __Marshaller_helloworld_HelloRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Helloworld.HelloRequest.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Helloworld.HelloReply> __Marshaller_helloworld_HelloReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Helloworld.HelloReply.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Helloworld.HelloEnumRequest> __Marshaller_helloworld_HelloEnumRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Helloworld.HelloEnumRequest.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Helloworld.HelloEnumReply> __Marshaller_helloworld_HelloEnumReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Helloworld.HelloEnumReply.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Helloworld.HelloOneOfRequest> __Marshaller_helloworld_HelloOneOfRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Helloworld.HelloOneOfRequest.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Helloworld.HelloOneOfReply> __Marshaller_helloworld_HelloOneOfReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Helloworld.HelloOneOfReply.Parser));

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Helloworld.HelloRequest, global::Helloworld.HelloReply> __Method_SayHello = new grpc::Method<global::Helloworld.HelloRequest, global::Helloworld.HelloReply>(
            grpc::MethodType.Unary,
            __ServiceName,
            "SayHello",
            __Marshaller_helloworld_HelloRequest,
            __Marshaller_helloworld_HelloReply);

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Helloworld.HelloEnumRequest, global::Helloworld.HelloEnumReply> __Method_SayHelloEnum = new grpc::Method<global::Helloworld.HelloEnumRequest, global::Helloworld.HelloEnumReply>(
            grpc::MethodType.Unary,
            __ServiceName,
            "SayHelloEnum",
            __Marshaller_helloworld_HelloEnumRequest,
            __Marshaller_helloworld_HelloEnumReply);

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Helloworld.HelloOneOfRequest, global::Helloworld.HelloOneOfReply> __Method_SayHelloOneOf = new grpc::Method<global::Helloworld.HelloOneOfRequest, global::Helloworld.HelloOneOfReply>(
            grpc::MethodType.Unary,
            __ServiceName,
            "SayHelloOneOf",
            __Marshaller_helloworld_HelloOneOfRequest,
            __Marshaller_helloworld_HelloOneOfReply);

        /// <summary>Service descriptor</summary>
        public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
        {
            get { return global::Helloworld.HelloReflection.Descriptor.Services[0]; }
        }

        /// <summary>Client for Greeter</summary>
        public partial class GreeterClient : grpc::ClientBase<GreeterClient>
        {
            /// <summary>Creates a new client for Greeter</summary>
            /// <param name="channel">The channel to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public GreeterClient(grpc::ChannelBase channel) : base(channel)
            {
            }
            /// <summary>Creates a new client for Greeter that uses a custom <c>CallInvoker</c>.</summary>
            /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public GreeterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
            {
            }
            /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected GreeterClient() : base()
            {
            }
            /// <summary>Protected constructor to allow creation of configured clients.</summary>
            /// <param name="configuration">The client configuration.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected GreeterClient(ClientBaseConfiguration configuration) : base(configuration)
            {
            }

            /// <summary>
            /// Sends a greeting
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
            /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
            /// <param name="cancellationToken">An optional token for canceling the call.</param>
            /// <returns>The response received from the server.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Helloworld.HelloReply SayHello(global::Helloworld.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// Sends a greeting
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="options">The options for the call.</param>
            /// <returns>The response received from the server.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Helloworld.HelloReply SayHello(global::Helloworld.HelloRequest request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
            }
            /// <summary>
            /// Sends a greeting
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
            /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
            /// <param name="cancellationToken">An optional token for canceling the call.</param>
            /// <returns>The call object.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Helloworld.HelloReply> SayHelloAsync(global::Helloworld.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            /// <summary>
            /// Sends a greeting
            /// </summary>
            /// <param name="request">The request to send to the server.</param>
            /// <param name="options">The options for the call.</param>
            /// <returns>The call object.</returns>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Helloworld.HelloReply> SayHelloAsync(global::Helloworld.HelloRequest request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Helloworld.HelloEnumReply SayHelloEnum(global::Helloworld.HelloEnumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SayHelloEnum(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Helloworld.HelloEnumReply SayHelloEnum(global::Helloworld.HelloEnumRequest request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_SayHelloEnum, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Helloworld.HelloEnumReply> SayHelloEnumAsync(global::Helloworld.HelloEnumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SayHelloEnumAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Helloworld.HelloEnumReply> SayHelloEnumAsync(global::Helloworld.HelloEnumRequest request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_SayHelloEnum, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Helloworld.HelloOneOfReply SayHelloOneOf(global::Helloworld.HelloOneOfRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SayHelloOneOf(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Helloworld.HelloOneOfReply SayHelloOneOf(global::Helloworld.HelloOneOfRequest request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_SayHelloOneOf, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Helloworld.HelloOneOfReply> SayHelloOneOfAsync(global::Helloworld.HelloOneOfRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return SayHelloOneOfAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Helloworld.HelloOneOfReply> SayHelloOneOfAsync(global::Helloworld.HelloOneOfRequest request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_SayHelloOneOf, null, options, request);
            }
            /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected override GreeterClient NewInstance(ClientBaseConfiguration configuration)
            {
                return new GreeterClient(configuration);
            }
        }

    }
}
#endregion
